# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# aux_links:
 #  Template Repository: https://github.com/just-the-docs/just-the-docs-template

title: Thoren Scientific
description: Thoren Scientific Webpage


# Uncomment one of the following themes:

theme: just-the-docs

# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# remote_theme: pages-themes/modernist@v0.2.0

url: https://thorenscientific.github.io/

aux_links:
  "Thorenscientific on GitHub":
    - "//github.com/thorenscientific/thorenscientific.github.io"

search_enabled: true

favicon_ico: "/favicon.ico"

# # theme: just-the-docs
# baseurl: "" # the subpath of your site, e.g. /blog
# url: https://thorenscientific.github.io

# repository: thorenscientific/thorenscientific.github.io # for github-metadata

# permalink: pretty

# Set a path/url to a logo that will be displayed instead of the title
logo: "/nerd_points_at_shiny_object.jpg"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 Thoren Scientific"