title: Thoren Scientific
description: Thoren Scientific Webpage
# theme: just-the-docs

url: https://thorenscientific.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
